<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Maheshs-Lenovo" ignored="0" name="TC_LoginTest_001" tests="1" failures="1" timestamp="24 Sep 2020 12:39:59 GMT" time="22.219" errors="0">
  <testcase name="loginTest" time="14.318" classname="com.nopcommerce.testcases.TC_LoginTest_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nopcommerce.testcases.TC_LoginTest_001.loginTest(TC_LoginTest_001.java:43)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
</testsuite> <!-- TC_LoginTest_001 -->
